name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - githubactions
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.29

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the action will use pre-installed Go.
          # skip-go-installation: true

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true
   name: Generate Report
   run: |
     pip install codecov
     pip install pytest-cov
     pytest --cov=./ --cov-report=xml
     codecov
   name: Upload coverage to Codecov
   uses: codecov/codecov-action@v3.1.0
   with:
     token: ${{ secrets.CODECOV_TOKEN }}
     directory: ./coverage/reports/
     env_vars: OS,PYTHON
     files: /home/runner/work/SIESTAstepper/SIESTAstepper/coverage.xml
     flags: tests
